### ISSUE TITLE
Validate slug field on form creation

### ISSUE THREAD

**Issue by lhenn** [lhenn/tasty-base#6]

**Comment by adam-coogan** [comment]
Summary of tonight's discussion

- Need backend to know whether it's being asked to update vs create a post.
- Ideally would accomplish this with custom API endpoints.
- Could also try grabbing all posts from Firebase, parsing their slugs and then submitting the post, but this is expensive and has timing edge cases.
- Could add a field like `actionType` to `content` indicating whether the write is an `edit` or `create`. This is hacky.
- On the other hand, slugs don't really matter, so we can drop them and use Firebase hashes as keys/slugs. This is really easy and fool-proof.
